# Generated by Django 5.0.4 on 2025-03-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheInternetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('interested', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
